# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: |
          cd functions
          npm install
      - name: Set Project id
        run: |
          echo PROJECT_ID=${{ secrets.PROJECT_ID }} >> $GITHUB_ENV
      - name: Environment Variables
        run: | 
          cd functions
          touch .env
          echo "SLACK_SECRET=${{ secrets.SLACK_SECRET }}" >> .env
          echo "SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}" >> .env
          echo "VERIFICATION_TOKEN=${{ secrets.VERIFICATION_TOKEN }}" >> .env
          echo "KIBELA_TOKEN=${{ secrets.KIBELA_TOKEN }}" >> .env
          echo "TEAM_NAME=${{ secrets.TEAM_NAME }}" >> .env
          less .env
      - name: Deploy to Firebase
        # uses: w9jds/firebase-action@master
        # with:
          # args: deploy --only functions
        run: | 
          cd functions
          npm run deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{env.PROJECT_ID}}
          # SLACK_SECRET: ${{ secrets.SLACK_SECRET }}
          # SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          # VERIFICATION_TOKEN: ${{ secrets.VERIFICATION_TOKEN }}
          # KIBELA_TOKEN: ${{ secrets.KIBELA_TOKEN }}
          # TEAM_NAME: ${{ secrets.TEAM_NAME }}
